# Generated by Django 4.2.23 on 2026-04-12 23:50

import core.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador / Jefe de carrera'), ('DOCENTE', 'Docente'), ('VISITANTE', 'Visitante')], default='VISITANTE', max_length=20)),
                ('password_temporal', models.CharField(blank=True, help_text='Contraseña temporal visible para el administrador.', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AtributoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atributo de egreso',
                'verbose_name_plural': 'Atributos de egreso',
            },
        ),
        migrations.CreateModel(
            name='CriterioDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atributo_egreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterios', to='core.atributoegreso')),
            ],
            options={
                'verbose_name': 'Criterio de desempeño',
                'verbose_name_plural': 'Criterios de desempeño',
                'unique_together': {('atributo_egreso', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicadores', to='core.criteriodesempeno')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'unique_together': {('criterio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('semestre', models.PositiveIntegerField()),
                ('es_especialidad', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['periodo', 'semestre', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='MateriaAtributoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_aporte', models.CharField(choices=[('I', 'Inicial'), ('M', 'Medio'), ('A', 'Avanzado')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atributo_egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atributoegreso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
            ],
            options={
                'verbose_name': 'Relación Materia–Atributo',
                'verbose_name_plural': 'Relaciones Materia–Atributo',
                'unique_together': {('materia', 'atributo_egreso')},
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_oferta', models.CharField(choices=[('PAR', 'Semestres pares (2, 4, 6, 8)'), ('IMPAR', 'Semestres impares (1, 3, 5, 7)')], default='PAR', max_length=10)),
                ('es_activo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReporteNivelLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_meta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_obtenido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia_atributo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_nivel_logro', to='core.materiaatributoegreso')),
            ],
            options={
                'verbose_name': 'Reporte de nivel de logro',
                'verbose_name_plural': 'Reportes de nivel de logro',
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='atributos_egreso',
            field=models.ManyToManyField(blank=True, related_name='materias', through='core.MateriaAtributoEgreso', to='core.atributoegreso'),
        ),
        migrations.AddField(
            model_name='materia',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='core.periodo'),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=core.models.ruta_evidencia)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.curso')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.materia'),
        ),
        migrations.CreateModel(
            name='ResultadoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('I', 'Inicial'), ('M', 'Medio'), ('A', 'Avanzado')], max_length=1)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_evaluacion', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_indicadores', to='core.curso')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='core.indicador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de indicador',
                'verbose_name_plural': 'Resultados de indicadores',
                'unique_together': {('curso', 'indicador')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('periodo', 'clave')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('materia', 'grupo')},
        ),
    ]
