# Generated by Django 4.2.23 on 2026-05-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciaindicador',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evidenciaindicador',
            name='tipo_archivo',
            field=models.CharField(choices=[('INSTRUMENTO', 'Instrumento de evaluación'), ('EVIDENCIA', 'Evidencia del estudiante'), ('REPORTE', 'Reporte de nivel de logro')], max_length=30),
        ),
    ]
