# Generated by Django 4.2.23 on 2026-05-06 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evidenciaindicador_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaReporteNivelLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='plantillas/reportes_nivel_logro/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='plantilla_reporte_nivel_logro', to='core.periodo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_reporte_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de reporte de nivel de logro',
                'verbose_name_plural': 'Plantillas de reporte de nivel de logro',
            },
        ),
    ]
