# Generated by Django 4.2.23 on 2026-04-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_password_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='tipo_oferta',
            field=models.CharField(choices=[('PAR', 'Semestres pares (2, 4, 6, 8)'), ('IMPAR', 'Semestres impares (1, 3, 5, 7)')], default='PAR', max_length=10),
        ),
    ]
