# Generated by Django 4.2.23 on 2026-05-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plantillareportenivellogro'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributoegreso',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atributos_egreso', to='core.periodo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atributoegreso',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='atributoegreso',
            unique_together={('periodo', 'codigo')},
        ),
    ]
