# Generated by Django 4.2.23 on 2026-05-16 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atributoegreso_periodo_alter_atributoegreso_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciaindicador',
            name='comentario_revision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidenciaindicador',
            name='estado_revision',
            field=models.CharField(choices=[('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='EN_REVISION', max_length=20),
        ),
        migrations.AddField(
            model_name='evidenciaindicador',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenciaindicador',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciaindicador',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
